// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpwg1BIfsO8iGedCPEGw0XYoLUo4M6TSw',
    appId: '1:707406560115:web:205f0601b2825151596306',
    messagingSenderId: '707406560115',
    projectId: 'tubes-pemob186',
    authDomain: 'tubes-pemob186.firebaseapp.com',
    storageBucket: 'tubes-pemob186.appspot.com',
    measurementId: 'G-F72JJFN48B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq7trALws9NHo3vGv5cO98itlfo29nUvw',
    appId: '1:707406560115:android:77875c1eb84ef33d596306',
    messagingSenderId: '707406560115',
    projectId: 'tubes-pemob186',
    storageBucket: 'tubes-pemob186.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2HzaMYeFdKMfmKkuYrydfh6VQWgrekiE',
    appId: '1:707406560115:ios:754f371a6d68a176596306',
    messagingSenderId: '707406560115',
    projectId: 'tubes-pemob186',
    storageBucket: 'tubes-pemob186.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2HzaMYeFdKMfmKkuYrydfh6VQWgrekiE',
    appId: '1:707406560115:ios:754f371a6d68a176596306',
    messagingSenderId: '707406560115',
    projectId: 'tubes-pemob186',
    storageBucket: 'tubes-pemob186.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
